name: webgate
version: '1.8.1'
summary: |
  Web-Service API for WebGate
description: |
  Webgate Project

architectures:
  - build-on: armhf
  - build-on: arm64
  - build-on: amd64
  - build-on: i386

confinement: devmode
base: core18

parts:
  WebGate:
    plugin: maven
    source: https://github.com/AlexRogalskiy/webgate.git
    source-tag: release-$SNAPCRAFT_PROJECT_VERSION
    maven-openjdk-version: "8"
    source-type: git
    source-branch: master
    maven-options:
      - -DskipTests=true
      - -Dmaven.javadoc.skip=false
      - -B
      - -V
      - -P"module_java","test-jar","xsd","dev"
    override-build: |
      snapcraftctl build
      unzip -o DIST/webgate-*.zip -d $SNAPCRAFT_PART_INSTALL/
    build-packages:
      - unzip

apps:
  WebGate:
    extensions:
      - gnome-3-28
    command: java $JAVA_OPTS -jar ./modules/webgate-mqtt-adapter/.build/bin/com.sensiblemetrics.api.webgate.mqtt.adapter/repackage/com.sensiblemetrics.api.webgate-mqtt-adapter-0.1.0-SNAPSHOT-exec.jar
    environment:
      JAVA_OPTS: -Xms1024m -Xmx1024m
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      PATH: $JAVA_HOME/jre/bin:$PATH
    plugs:
      - home
      - network
      - network-bind
