# SensibleMetrics WebGate MQTT Adapter Cloud configuration
---
spring:
  cloud:
    consul:
      discovery:
        instance-id: 1
    kubernetes:
      discovery:
        enabled: false
      enabled: false
