name: Syntax-checking

on:
  push:
    branches-ignore: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare git
        run: git config --global core.autocrlf false

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: jsonlint
        uses: docker://github/super-linter:v3@sha256:ba505b27d8b604b7b5b2250f0a9420cffca61f2ca55cfb39ac6f581f3c189855
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JSON: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
